[package]
name = "fn0-ski"
version = "0.1.12"
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Minimal Winter CG Compatible Runtime"

[dependencies]
base64 = { workspace = true }
bytes = { workspace = true }
deno_core = { workspace = true }
deno_crypto = { package = "fn0-deno-crypto", version = "=0.255.0", path = "../../vendor/deno/ext/crypto" }
deno_error = { workspace = true }
deno_fetch = { package = "fn0-deno-fetch", version = "=0.250.0", path = "../../vendor/deno/ext/fetch" }
deno_web = { package = "fn0-deno-web", version = "=0.257.0", path = "../../vendor/deno/ext/web" }
deno_webidl = { workspace = true }
encoding_rs = { workspace = true }
futures = { workspace = true }
http = { workspace = true }
http-body-util = { workspace = true }
hyper = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["full"] }
tokio-util = { workspace = true }

[build-dependencies]
deno_core = { workspace = true }
deno_crypto = { package = "fn0-deno-crypto", version = "=0.255.0", path = "../../vendor/deno/ext/crypto" }
deno_error = { workspace = true }
deno_fetch = { package = "fn0-deno-fetch", version = "=0.250.0", path = "../../vendor/deno/ext/fetch" }
deno_web = { package = "fn0-deno-web", version = "=0.257.0", path = "../../vendor/deno/ext/web" }
deno_webidl = { workspace = true }
