[package]
name = "forte-sdk"
version = "0.9.0"
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Runtime library for Forte wasm components (wasi:http p3)"

[features]
test-harness = ["dep:inventory"]

[build-dependencies]
forte-wit = { workspace = true }

[dependencies]
anyhow = { workspace = true, features = ["backtrace"] }
bytes = { workspace = true }
chrono = { workspace = true, features = ["serde"] }
cookie = { workspace = true, features = ["percent-encode"] }
form_urlencoded = { workspace = true }
forte-json = { workspace = true }
forte-macros = { workspace = true }
futures = { workspace = true }
hex = { workspace = true }
hmac = { workspace = true }
http = { workspace = true }
http-body = { workspace = true }
http-body-util = { workspace = true }
inventory = { workspace = true, optional = true }
opentelemetry = { workspace = true }
opentelemetry-proto = { workspace = true, default-features = false, features = ["gen-tonic-messages", "trace", "metrics"] }
opentelemetry_sdk = { workspace = true, default-features = false, features = ["trace", "metrics", "experimental_metrics_custom_reader"] }
prost = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
sha2 = { workspace = true }
time = { workspace = true }
tracing = { workspace = true }
tracing-opentelemetry = { workspace = true, default-features = false }
tracing-subscriber = { workspace = true, default-features = false, features = ["registry", "fmt", "env-filter", "std"] }
uuid = { workspace = true, features = ["v7"] }
wit-bindgen = { workspace = true }
