[package]
name = "fn0-worker"
version = "0.4.12"
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Worker binary for the fn0 FaaS platform"

[dependencies]
aes-gcm = { workspace = true }
anyhow = { workspace = true }
async-trait = { workspace = true }
async_singleflight = { workspace = true }
base64 = { workspace = true }
bytes = { workspace = true }
color-eyre = { workspace = true }
dashmap = { workspace = true }
doc-db = { workspace = true }
fn0 = { workspace = true }
fn0-shared-schema = { workspace = true }
futures = { workspace = true }
fastwebsockets = { workspace = true, features = ["upgrade", "unstable-split"] }
hmac = { workspace = true }
http = { workspace = true }
http-body = { workspace = true }
http-body-util = { workspace = true }
oci-rust-sdk = { workspace = true }
hyper = { workspace = true, features = ["full"] }
hyper-util = { workspace = true, features = ["full"] }
mimalloc = { workspace = true }
opendal = { workspace = true }
opentelemetry = { workspace = true, features = ["logs", "metrics"] }
opentelemetry-appender-tracing = { workspace = true }
opentelemetry-http = { workspace = true, features = ["reqwest"] }
opentelemetry-otlp = { workspace = true, features = ["http-proto", "reqwest-client", "metrics", "logs"] }
opentelemetry_sdk = { workspace = true, features = ["logs", "rt-tokio", "spec_unstable_metrics_views"] }
reqwest = { workspace = true }
quinn = { workspace = true, default-features = false, features = ["runtime-tokio", "rustls-aws-lc-rs"] }
rand = { workspace = true }
rustls = { workspace = true }
rustls-pemfile = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
sha1 = { workspace = true }
sha2 = { workspace = true }
tar = { workspace = true }
tokio = { workspace = true, features = ["full"] }
tokio-rustls = { workspace = true }
tokio-util = { workspace = true, features = ["io"] }
tracing = { workspace = true }
tracing-opentelemetry = { workspace = true }
tracing-subscriber = { workspace = true }
url = { workspace = true }
webpki-roots = { workspace = true }
zstd = { workspace = true }

[dev-dependencies]
rcgen = { workspace = true }
