use super::model::*;
use proc_macro2::TokenStream;
use quote::{format_ident, quote};
use std::collections::BTreeMap;

#[allow(clippy::too_many_arguments)]
pub(super) fn generate_code(
    pages: &[PageInfo],
    hooks: &[HookInfo],
    actions: &[ActionInfo],
    queue_tasks: &[QueueTaskInfo],
    admin_tasks: &[AdminTaskInfo],
    static_files: &[StaticFileInfo],
    websockets: &[WebSocketRouteInfo],
    wit_dir: &str,
) -> TokenStream {
    let mut all_module_decls: Vec<(String, TokenStream)> = Vec::new();
    for (name, ts) in generate_module_declarations(pages) {
        all_module_decls.push((name, ts));
    }
    for (name, ts) in generate_hook_module_declarations(hooks) {
        all_module_decls.push((name, ts));
    }
    for (name, ts) in generate_action_module_declarations(actions) {
        all_module_decls.push((name, ts));
    }
    for (name, ts) in generate_websocket_module_declarations(websockets) {
        all_module_decls.push((name, ts));
    }
    all_module_decls.sort_by(|(a, _), (b, _)| a.cmp(b));
    let module_declarations: Vec<TokenStream> =
        all_module_decls.into_iter().map(|(_, ts)| ts).collect();
    let hook_module_declarations: Vec<TokenStream> = Vec::new();
    let action_module_declarations: Vec<TokenStream> = Vec::new();
    let route_matches = generate_route_matches(pages);
    let redirect_enum = generate_redirect_enum(pages);
    let hook_handler = generate_hook_handler(hooks);
    let action_handler = generate_action_handler(actions);
    let enqueue_module = generate_enqueue_module(queue_tasks);
    let queue_task_execute_handler = generate_queue_task_execute_handler(queue_tasks);
    let admin_task_handler = generate_admin_task_handler(admin_tasks);
    let classify_route_fn = generate_classify_route(pages);
    let cache_policy_handler = generate_cache_policy_handler(pages);
    let websocket_handler = generate_websocket_handler(websockets);
    let websocket_path_module = generate_websocket_path_module(websockets);

    let static_file_chain = {
        let matches: Vec<TokenStream> = static_files
            .iter()
            .map(|f| {
                let route_path = &f.route_path;
                let content_type = &f.content_type;
                let include_path = &f.include_path;
                quote! {
                    if path == #route_path {
                        return Ok(Response::builder()
                            .status(StatusCode::OK)
                            .header("content-type", #content_type)
                            .body(Body::from(include_bytes!(#include_path).to_vec()))
                            .unwrap());
                    }
                }
            })
            .collect();
        quote! { #(#matches)* }
    };

    let route_chain = if route_matches.is_empty() {
        quote! {
            Ok(Response::builder()
                .status(StatusCode::NOT_FOUND)
                .body(Body::empty())
                .unwrap())
        }
    } else {
        let needs_path_segments = pages
            .iter()
            .any(|p| has_dynamic_segments(&p.route_segments));
        let path_segments_decl = if needs_path_segments {
            quote! {
                let path_segments: Vec<&str> = path.trim_start_matches('/').split('/').collect();
            }
        } else {
            quote! {}
        };
        let first = &route_matches[0];
        let rest = &route_matches[1..];
        quote! {
            #path_segments_decl
            #first
            #(else #rest)*
            else {
                Ok(Response::builder()
                    .status(StatusCode::NOT_FOUND)
                    .body(Body::empty())
                    .unwrap())
            }
        }
    };

    let proxy_world_inline = "package forte:user; world service-export { import wasi:http/types@0.3.0; export wasi:http/handler@0.3.0; }";

    quote! {
        // Auto-generated by build.rs

        #(#module_declarations)*
        #(#hook_module_declarations)*
        #(#action_module_declarations)*
        #websocket_path_module

        use forte_sdk::anyhow::Result;
        use forte_sdk::http::{Request, Response, StatusCode, body::Body, HeaderMap};
        use forte_sdk::http_header::{COOKIE, LOCATION, SET_COOKIE};
        use forte_sdk::*;

        #redirect_enum

        #enqueue_module

        #[allow(clippy::crate_in_macro_def)]
        mod proxy {
            forte_sdk::wit_bindgen::generate!({
                inline: #proxy_world_inline,
                path: #wit_dir,
                world: "service-export",
                default_bindings_module: "crate::route_generated::proxy",
                pub_export_macro: true,
                features: ["clocks-timezone"],
                with: {
                    "wasi:http/handler@0.3.0": generate,
                    "wasi:http/types@0.3.0": forte_sdk::bindings::wasi::http::types,
                    "wasi:clocks/types@0.3.0": forte_sdk::bindings::wasi::clocks::types,
                },
                runtime_path: "forte_sdk::wit_bindgen::rt",
            });
        }

        struct Server;

        impl proxy::exports::wasi::http::handler::Guest for Server {
            async fn handle(
                req: forte_sdk::bindings::wasi::http::types::Request,
            ) -> core::result::Result<
                forte_sdk::bindings::wasi::http::types::Response,
                forte_sdk::bindings::wasi::http::types::ErrorCode,
            > {
                forte_sdk::serve::serve(req, |request| async move {
                    dispatch(request).await
                }).await
            }
        }

        proxy::export!(Server);

        async fn dispatch(request: Request<Body>) -> Result<Response<Body>> {
            let path_for_route = request.uri().path().to_string();
            let key = classify_route(&path_for_route);
            let result = dispatch_inner(request).await;
            result.map(|mut resp| {
                if let Ok(v) = forte_sdk::http::HeaderValue::from_str(&key) {
                    resp.headers_mut().insert("x-fn0-execution-time-metric-key", v);
                }
                resp
            })
        }

        #classify_route_fn

        #cache_policy_handler

        async fn dispatch_inner(request: Request<Body>) -> Result<Response<Body>> {
            let (parts, body) = request.into_parts();
            let headers = parts.headers;
            let uri = parts.uri;
            let path = uri.path().to_string();
            let method = parts.method;

            if path == "/__fn0_cache_policy" {
                return handle_cache_policy(&method, &headers).await;
            }

            let mut cookie_jar = make_cookie_jar(&headers);

            let Some(uri_authority) = uri.authority() else {
                return Ok(Response::builder()
                    .status(StatusCode::BAD_REQUEST)
                    .body(Body::from("Missing authority in request URI"))
                    .unwrap());
            };
            let uri_authority = uri_authority.as_str();
            let path = path.as_str();

            if let Some(hook_name) = path.strip_prefix("/__self_invoke/") {
                let body_bytes = body
                    .bytes_limited(forte_sdk::http::DEFAULT_BODY_BUFFER_LIMIT)
                    .await?;
                return handle_hook(hook_name, uri_authority, &method, &headers, &mut cookie_jar, &body_bytes).await;
            }

            if let Some(action_name) = path.strip_prefix("/__forte_action/") {
                let body_bytes = body
                    .bytes_limited(forte_sdk::http::DEFAULT_BODY_BUFFER_LIMIT)
                    .await?;
                return handle_action(action_name, uri_authority, &method, &headers, &mut cookie_jar, &body_bytes).await;
            }

            if path == "/__fn0_queue_task/execute" {
                let body_bytes = body
                    .bytes_limited(forte_sdk::http::DEFAULT_BODY_BUFFER_LIMIT)
                    .await?;
                return handle_queue_task_execute(&body_bytes).await;
            }

            if let Some(task_name) = path.strip_prefix("/__forte_admin/") {
                let body_bytes = body
                    .bytes_limited(forte_sdk::http::DEFAULT_BODY_BUFFER_LIMIT)
                    .await?;
                return handle_admin_task(task_name, &headers, &body_bytes).await;
            }

            if headers.contains_key("x-fn0-internal-websocket-event") {
                let body_bytes = body
                    .bytes_limited(forte_sdk::http::DEFAULT_BODY_BUFFER_LIMIT)
                    .await?;
                return handle_websocket_event(path, uri, headers, body_bytes.to_vec()).await;
            }

            if path == "/ws" || path.starts_with("/ws/") {
                return Ok(Response::builder()
                    .status(StatusCode::UPGRADE_REQUIRED)
                    .body(Body::empty())
                    .unwrap());
            }

            #static_file_chain

            #route_chain
        }

        #hook_handler

        #action_handler

        #queue_task_execute_handler

        #admin_task_handler

        #websocket_handler

        fn make_cookie_jar(headers: &HeaderMap) -> cookie::CookieJar {
            let mut jar = cookie::CookieJar::new();
            let Some(cookie) = headers.get(COOKIE) else {
                return jar;
            };
            let Ok(cookie_str) = cookie.to_str() else {
                return jar;
            };

            for cookie in cookie::Cookie::split_parse_encoded(cookie_str) {
                let Ok(cookie) = cookie else { continue };
                jar.add_original(cookie.into_owned());
            }

            jar
        }

        fn build_response_with_cookies(mut response: Response<Body>, cookie_jar: &cookie::CookieJar) -> Response<Body> {
            for cookie in cookie_jar.delta() {
                if let Ok(value) = cookie.encoded().to_string().parse() {
                    response.headers_mut().append(SET_COOKIE, value);
                }
            }
            response
        }
    }
}

fn generate_module_declarations(pages: &[PageInfo]) -> Vec<(String, TokenStream)> {
    pages
        .iter()
        .map(|page| {
            let module_ident = format_ident!("{}", page.module_name);
            let module_path = &page.module_path;

            let allow_attr = if has_dynamic_segments(&page.route_segments) {
                quote! { #[allow(non_snake_case)] }
            } else {
                quote! {}
            };

            (
                page.module_name.clone(),
                quote! {
                    #allow_attr
                    #[path = #module_path]
                    mod #module_ident;
                },
            )
        })
        .collect()
}

fn generate_websocket_module_declarations(
    websockets: &[WebSocketRouteInfo],
) -> Vec<(String, TokenStream)> {
    websockets
        .iter()
        .map(|websocket| {
            let module_ident = format_ident!("{}", websocket.module_name);
            let module_path = &websocket.module_path;
            let allow_attribute = if has_dynamic_segments(&websocket.route_segments) {
                quote! { #[allow(non_snake_case)] }
            } else {
                quote! {}
            };
            (
                websocket.module_name.clone(),
                quote! {
                    #allow_attribute
                    #[path = #module_path]
                    mod #module_ident;
                },
            )
        })
        .collect()
}

#[derive(Default)]
struct WebSocketPathNode {
    children: BTreeMap<String, WebSocketPathNode>,
    route_path: Option<String>,
}

fn generate_websocket_path_module(websockets: &[WebSocketRouteInfo]) -> TokenStream {
    if websockets.is_empty() {
        return quote! {};
    }

    let mut root = WebSocketPathNode::default();
    for websocket in websockets
        .iter()
        .filter(|websocket| matches!(websocket.direction, WebSocketDirection::Outbound))
    {
        let mut node = &mut root;
        for module_segment in &websocket.module_segments {
            node = node.children.entry(module_segment.clone()).or_default();
        }
        node.route_path = Some(websocket.route_path.clone());
    }

    generate_websocket_path_node(&root)
}

fn generate_websocket_path_node(node: &WebSocketPathNode) -> TokenStream {
    let children = node.children.iter().map(|(module_segment, child)| {
        let module_ident = format_ident!("{}", module_segment);
        let child_body = generate_websocket_path_node(child);
        quote! {
            pub mod #module_ident {
                #child_body
            }
        }
    });
    let path_constant = node.route_path.as_ref().map(|route_path| {
        quote! {
            const PATH: &str = #route_path;

            pub async fn connect(
                url: impl Into<String>,
            ) -> core::result::Result<
                forte_sdk::websocket::ConnectionId,
                forte_sdk::websocket::WebSocketConnectError,
            > {
                forte_sdk::websocket::connect(url, PATH).await
            }
        }
    });

    quote! {
        #(#children)*
        #path_constant
    }
}

fn generate_websocket_handler(websockets: &[WebSocketRouteInfo]) -> TokenStream {
    if websockets.is_empty() {
        return quote! {
            async fn handle_websocket_event(
                _path: &str,
                _uri: forte_sdk::http::Uri,
                _headers: HeaderMap,
                _body_bytes: Vec<u8>,
            ) -> Result<Response<Body>> {
                Ok(Response::builder()
                    .status(StatusCode::NOT_FOUND)
                    .body(Body::empty())
                    .unwrap())
            }
        };
    }
    let route_matches: Vec<TokenStream> = websockets
        .iter()
        .map(generate_websocket_route_match)
        .collect();
    let first_match = &route_matches[0];
    let remaining_matches = &route_matches[1..];
    let route_chain = quote! {
        #first_match
        #(else #remaining_matches)*
        else {
            Ok(Response::builder()
                .status(StatusCode::NOT_FOUND)
                .body(Body::empty())
                .unwrap())
        }
    };

    quote! {
        async fn handle_websocket_event(
            path: &str,
            uri: forte_sdk::http::Uri,
            headers: HeaderMap,
            body_bytes: Vec<u8>,
        ) -> Result<Response<Body>> {
            let path_segments: Vec<&str> = path.trim_start_matches('/').split('/').collect();
            #route_chain
        }

        fn websocket_public_headers(headers: &HeaderMap) -> HeaderMap {
            let mut public_headers = HeaderMap::new();
            for (header_name, header_value) in headers {
                if !header_name.as_str().starts_with("x-fn0-") {
                    public_headers.append(header_name.clone(), header_value.clone());
                }
            }
            public_headers
        }

        fn websocket_response_headers_valid(headers: &HeaderMap) -> bool {
            headers.keys().all(|header_name| {
                !matches!(
                    header_name.as_str(),
                    "connection"
                        | "upgrade"
                        | "sec-websocket-accept"
                        | "sec-websocket-protocol"
                        | "content-length"
                        | "transfer-encoding"
                ) && !header_name.as_str().starts_with("x-fn0-")
                    && !header_name.as_str().starts_with("sec-websocket-")
            })
        }

        fn websocket_error_response(status: StatusCode) -> Response<Body> {
            Response::builder()
                .status(status)
                .body(Body::empty())
                .unwrap()
        }
    }
}

fn generate_websocket_route_match(websocket: &WebSocketRouteInfo) -> TokenStream {
    if websocket.direction == WebSocketDirection::Singleton {
        return generate_websocket_singleton_route_match(websocket);
    }
    let module_name = format_ident!("{}", websocket.module_name);
    let route_condition = if has_dynamic_segments(&websocket.route_segments) {
        generate_dynamic_route_condition(&websocket.route_segments)
    } else {
        let route_path = &websocket.route_path;
        quote! { path == #route_path }
    };
    let path_params_extraction = if let Some(path_params) = &websocket.path_params {
        generate_path_params_extraction(&module_name, &websocket.route_segments, path_params)
    } else {
        quote! {}
    };
    let connect_branch = match websocket.direction {
        WebSocketDirection::Inbound => {
            generate_websocket_inbound_connect_branch(&module_name, websocket.path_params.is_some())
        }
        WebSocketDirection::Outbound => {
            quote! {
                "connect" => Ok(websocket_error_response(StatusCode::NOT_FOUND)),
            }
        }
        WebSocketDirection::Singleton => unreachable!(),
    };
    let message_call =
        websocket_callback_call(&module_name, "on_message", websocket.path_params.is_some());
    let disconnect_call = if websocket.has_on_disconnect {
        websocket_callback_call(
            &module_name,
            "on_disconnect",
            websocket.path_params.is_some(),
        )
    } else {
        quote! { Ok::<(), forte_sdk::anyhow::Error>(()) }
    };

    quote! {
        if #route_condition {
            #path_params_extraction
            let Some(connection_id_value) = headers
                .get("x-fn0-internal-websocket-connection-id")
                .and_then(|value| value.to_str().ok())
            else {
                return Ok(websocket_error_response(StatusCode::BAD_REQUEST));
            };
            let connection_id = forte_sdk::websocket::ConnectionId::new(connection_id_value);
            let Some(event_name) = headers
                .get("x-fn0-internal-websocket-event")
                .and_then(|value| value.to_str().ok())
            else {
                return Ok(websocket_error_response(StatusCode::BAD_REQUEST));
            };
            match event_name {
                #connect_branch
                "message" => {
                    let message = match headers
                        .get("x-fn0-internal-websocket-message-kind")
                        .and_then(|value| value.to_str().ok())
                    {
                        Some("text") => match String::from_utf8(body_bytes) {
                            Ok(text) => forte_sdk::websocket::IncomingMessage::Text(text),
                            Err(_) => return Ok(websocket_error_response(StatusCode::BAD_REQUEST)),
                        },
                        Some("binary") => forte_sdk::websocket::IncomingMessage::Binary(body_bytes),
                        _ => return Ok(websocket_error_response(StatusCode::BAD_REQUEST)),
                    };
                    let event = forte_sdk::websocket::MessageEvent {
                        connection_id,
                        message,
                    };
                    match #message_call {
                        Ok(()) => Ok(websocket_error_response(StatusCode::NO_CONTENT)),
                        Err(error) => {
                            eprintln!("WebSocket on_message error at {}: {:?}", path, error);
                            Ok(websocket_error_response(StatusCode::INTERNAL_SERVER_ERROR))
                        }
                    }
                }
                "disconnect" => {
                    let close_code = headers
                        .get("x-fn0-internal-websocket-close-code")
                        .and_then(|value| value.to_str().ok())
                        .and_then(|value| value.parse::<u16>().ok());
                    let reason = headers
                        .get("x-fn0-internal-websocket-close-reason")
                        .and_then(|value| value.to_str().ok())
                        .map(str::to_string);
                    let cause = match headers
                        .get("x-fn0-internal-websocket-disconnect-cause")
                        .and_then(|value| value.to_str().ok())
                    {
                        Some("peer") => forte_sdk::websocket::DisconnectCause::Peer,
                        Some("application") => forte_sdk::websocket::DisconnectCause::Application,
                        Some("deployment") => forte_sdk::websocket::DisconnectCause::Deployment,
                        Some("heartbeat-timeout") => forte_sdk::websocket::DisconnectCause::HeartbeatTimeout,
                        Some("protocol-error") => forte_sdk::websocket::DisconnectCause::ProtocolError,
                        Some("transport-error") => forte_sdk::websocket::DisconnectCause::TransportError,
                        _ => forte_sdk::websocket::DisconnectCause::InternalError,
                    };
                    let event = forte_sdk::websocket::DisconnectEvent {
                        connection_id,
                        close_code,
                        reason,
                        cause,
                    };
                    match #disconnect_call {
                        Ok(()) => Ok(websocket_error_response(StatusCode::NO_CONTENT)),
                        Err(error) => {
                            eprintln!("WebSocket on_disconnect error at {}: {:?}", path, error);
                            Ok(websocket_error_response(StatusCode::INTERNAL_SERVER_ERROR))
                        }
                    }
                }
                _ => Ok(websocket_error_response(StatusCode::BAD_REQUEST)),
            }
        }
    }
}

fn generate_websocket_singleton_route_match(websocket: &WebSocketRouteInfo) -> TokenStream {
    let module_name = format_ident!("{}", websocket.module_name);
    let route_path = &websocket.route_path;
    let initialize_call = quote! { #module_name::connect().await };
    let connect_call = if websocket.has_on_connect {
        quote! { #module_name::on_connect(event).await }
    } else {
        quote! { Ok::<(), forte_sdk::anyhow::Error>(()) }
    };
    let message_call = quote! { #module_name::on_message(event).await };
    let disconnect_call = if websocket.has_on_disconnect {
        quote! { #module_name::on_disconnect(event).await }
    } else {
        quote! { Ok::<(), forte_sdk::anyhow::Error>(()) }
    };

    quote! {
        if path == #route_path {
            let Some(event_name) = headers
                .get("x-fn0-internal-websocket-event")
                .and_then(|value| value.to_str().ok())
            else {
                return Ok(websocket_error_response(StatusCode::BAD_REQUEST));
            };
            if event_name == "initialize" {
                return match #initialize_call {
                    Ok(options) => {
                        let mut serialized_headers = Vec::new();
                        for (header_name, header_value) in &options.headers {
                            let Ok(header_value) = header_value.to_str() else {
                                return Ok(websocket_error_response(StatusCode::INTERNAL_SERVER_ERROR));
                            };
                            serialized_headers.push((header_name.as_str(), header_value));
                        }
                        let body = forte_sdk::serde_json::to_vec(&forte_sdk::serde_json::json!({
                            "url": options.url,
                            "headers": serialized_headers,
                            "protocols": options.protocols,
                        }))?;
                        Ok(Response::builder()
                            .status(StatusCode::OK)
                            .header("content-type", "application/json")
                            .body(Body::from(body))
                            .unwrap())
                    }
                    Err(_) => {
                        eprintln!("WebSocket singleton initialization failed at {}", path);
                        Ok(websocket_error_response(StatusCode::INTERNAL_SERVER_ERROR))
                    }
                };
            }
            let Some(connection_id_value) = headers
                .get("x-fn0-internal-websocket-connection-id")
                .and_then(|value| value.to_str().ok())
            else {
                return Ok(websocket_error_response(StatusCode::BAD_REQUEST));
            };
            let connection_id = forte_sdk::websocket::ConnectionId::new(connection_id_value);
            match event_name {
                "connect" => {
                    let event = forte_sdk::websocket::SingletonConnectEvent {
                        connection_id,
                        protocol: headers
                            .get("sec-websocket-protocol")
                            .and_then(|value| value.to_str().ok())
                            .map(str::to_string),
                    };
                    match #connect_call {
                        Ok(()) => Ok(websocket_error_response(StatusCode::NO_CONTENT)),
                        Err(error) => {
                            eprintln!("WebSocket singleton on_connect failed at {}: {:?}", path, error);
                            Ok(websocket_error_response(StatusCode::INTERNAL_SERVER_ERROR))
                        }
                    }
                }
                "message" => {
                    let message = match headers
                        .get("x-fn0-internal-websocket-message-kind")
                        .and_then(|value| value.to_str().ok())
                    {
                        Some("text") => match String::from_utf8(body_bytes) {
                            Ok(text) => forte_sdk::websocket::IncomingMessage::Text(text),
                            Err(_) => return Ok(websocket_error_response(StatusCode::BAD_REQUEST)),
                        },
                        Some("binary") => forte_sdk::websocket::IncomingMessage::Binary(body_bytes),
                        _ => return Ok(websocket_error_response(StatusCode::BAD_REQUEST)),
                    };
                    let event = forte_sdk::websocket::MessageEvent {
                        connection_id,
                        message,
                    };
                    match #message_call {
                        Ok(()) => Ok(websocket_error_response(StatusCode::NO_CONTENT)),
                        Err(error) => {
                            eprintln!("WebSocket singleton on_message failed at {}: {:?}", path, error);
                            Ok(websocket_error_response(StatusCode::INTERNAL_SERVER_ERROR))
                        }
                    }
                }
                "disconnect" => {
                    let close_code = headers
                        .get("x-fn0-internal-websocket-close-code")
                        .and_then(|value| value.to_str().ok())
                        .and_then(|value| value.parse::<u16>().ok());
                    let reason = headers
                        .get("x-fn0-internal-websocket-close-reason")
                        .and_then(|value| value.to_str().ok())
                        .map(str::to_string);
                    let cause = match headers
                        .get("x-fn0-internal-websocket-disconnect-cause")
                        .and_then(|value| value.to_str().ok())
                    {
                        Some("peer") => forte_sdk::websocket::DisconnectCause::Peer,
                        Some("application") => forte_sdk::websocket::DisconnectCause::Application,
                        Some("deployment") => forte_sdk::websocket::DisconnectCause::Deployment,
                        Some("heartbeat-timeout") => forte_sdk::websocket::DisconnectCause::HeartbeatTimeout,
                        Some("protocol-error") => forte_sdk::websocket::DisconnectCause::ProtocolError,
                        Some("transport-error") => forte_sdk::websocket::DisconnectCause::TransportError,
                        _ => forte_sdk::websocket::DisconnectCause::InternalError,
                    };
                    let event = forte_sdk::websocket::DisconnectEvent {
                        connection_id,
                        close_code,
                        reason,
                        cause,
                    };
                    match #disconnect_call {
                        Ok(()) => Ok(websocket_error_response(StatusCode::NO_CONTENT)),
                        Err(error) => {
                            eprintln!("WebSocket singleton on_disconnect failed at {}: {:?}", path, error);
                            Ok(websocket_error_response(StatusCode::INTERNAL_SERVER_ERROR))
                        }
                    }
                }
                _ => Ok(websocket_error_response(StatusCode::BAD_REQUEST)),
            }
        }
    }
}

fn generate_websocket_inbound_connect_branch(
    module_name: &syn::Ident,
    has_path_params: bool,
) -> TokenStream {
    let connect_call = websocket_callback_call(module_name, "on_connect", has_path_params);
    quote! {
        "connect" => {
            let requested_protocols = headers
                .get_all("sec-websocket-protocol")
                .iter()
                .filter_map(|value| value.to_str().ok())
                .flat_map(|value| value.split(','))
                .map(str::trim)
                .filter(|value| !value.is_empty())
                .map(str::to_string)
                .collect();
            let client_address = headers
                .get("x-fn0-internal-websocket-client-address")
                .and_then(|value| value.to_str().ok())
                .map(str::to_string);
            let event = forte_sdk::websocket::ConnectEvent {
                connection_id,
                uri,
                headers: websocket_public_headers(&headers),
                client_address,
                requested_protocols,
            };
            match #connect_call {
                Ok(forte_sdk::websocket::ConnectDecision::Accept {
                    protocol,
                    headers: response_headers,
                }) => {
                    if !websocket_response_headers_valid(&response_headers) {
                        return Ok(websocket_error_response(StatusCode::INTERNAL_SERVER_ERROR));
                    }
                    let mut response = Response::builder()
                        .status(StatusCode::NO_CONTENT)
                        .body(Body::empty())
                        .unwrap();
                    *response.headers_mut() = response_headers;
                    response.headers_mut().insert(
                        "x-fn0-internal-websocket-decision",
                        "accept".parse().unwrap(),
                    );
                    if let Some(protocol) = protocol {
                        let Ok(protocol_header) = protocol.parse() else {
                            return Ok(websocket_error_response(StatusCode::INTERNAL_SERVER_ERROR));
                        };
                        response.headers_mut().insert(
                            "x-fn0-internal-websocket-protocol",
                            protocol_header,
                        );
                    }
                    Ok(response)
                }
                Ok(forte_sdk::websocket::ConnectDecision::Reject {
                    status,
                    headers: response_headers,
                }) => {
                    if status == StatusCode::SWITCHING_PROTOCOLS
                        || !websocket_response_headers_valid(&response_headers)
                    {
                        return Ok(websocket_error_response(StatusCode::INTERNAL_SERVER_ERROR));
                    }
                    let mut response = Response::builder()
                        .status(status)
                        .body(Body::empty())
                        .unwrap();
                    *response.headers_mut() = response_headers;
                    response.headers_mut().insert(
                        "x-fn0-internal-websocket-decision",
                        "reject".parse().unwrap(),
                    );
                    Ok(response)
                }
                Err(error) => {
                    eprintln!("WebSocket on_connect error at {}: {:?}", path, error);
                    Ok(websocket_error_response(StatusCode::INTERNAL_SERVER_ERROR))
                }
            }
        }
    }
}

fn websocket_callback_call(
    module_name: &syn::Ident,
    callback_name: &str,
    has_path_params: bool,
) -> TokenStream {
    let callback_ident = format_ident!("{callback_name}");
    if has_path_params {
        quote! { #module_name::#callback_ident(event, path_params).await }
    } else {
        quote! { #module_name::#callback_ident(event).await }
    }
}

fn has_dynamic_segments(segments: &[RouteSegment]) -> bool {
    segments
        .iter()
        .any(|s| matches!(s, RouteSegment::Dynamic(_)))
}

fn generate_hook_module_declarations(hooks: &[HookInfo]) -> Vec<(String, TokenStream)> {
    hooks
        .iter()
        .map(|hook| {
            let module_ident = format_ident!("{}", hook.module_name);
            let module_path = &hook.module_path;

            (
                hook.module_name.clone(),
                quote! {
                    #[path = #module_path]
                    mod #module_ident;
                },
            )
        })
        .collect()
}

fn generate_route_matches(pages: &[PageInfo]) -> Vec<TokenStream> {
    pages
        .iter()
        .map(|page| {
            let module_name = format_ident!("{}", page.module_name);

            // Generate route condition
            let route_condition = if has_dynamic_segments(&page.route_segments) {
                generate_dynamic_route_condition(&page.route_segments)
            } else {
                let route_path = &page.route_path;
                quote! { path == #route_path }
            };


            // Generate path params extraction (if dynamic)
            let path_params_extraction = if let Some(path_params) = &page.path_params {
                generate_path_params_extraction(&module_name, &page.route_segments, path_params)
            } else {
                quote! {}
            };

            let search_params_extraction = if let Some(fields) = &page.search_params {
                let field_parsers = generate_search_field_parsers(fields);
                let field_names: Vec<_> =
                    fields.iter().map(|f| format_ident!("{}", f.name)).collect();
                quote! {
                    use std::collections::HashMap;
                    let query = uri.query().unwrap_or("");
                    let query_params: HashMap<String, String> = forte_sdk::form_urlencoded::parse(query.as_bytes())
                        .map(|(k, v)| (k.into_owned(), v.into_owned()))
                        .collect();
                    #(#field_parsers)*
                    let search_params = #module_name::SearchParams {
                        #(#field_names),*
                    };
                }
            } else {
                quote! {}
            };

            // Generate handler call based on what params exist
            let handler_call = match (&page.path_params, &page.search_params) {
                (Some(_), Some(_)) => quote! {
                    #module_name::handler(req, path_params, search_params).await
                },
                (Some(_), None) => quote! {
                    #module_name::handler(req, path_params).await
                },
                (None, Some(_)) => quote! {
                    #module_name::handler(req, search_params).await
                },
                (None, None) => quote! {
                    #module_name::handler(req).await
                },
            };

            let response_handling = match page.response_kind {
                HandlerResponseKind::RedirectOnly => quote! {
                    match #handler_call {
                        Ok(redirect) => {
                            Ok(build_response_with_cookies(
                                Response::builder()
                                    .status(StatusCode::FOUND)
                                    .header(LOCATION, redirect.to_path())
                                    .body(Body::empty())
                                    .unwrap(),
                                &cookie_jar,
                            ))
                        }
                        Err(e) => {
                            eprintln!("Error at {}: {:?}", path, e);
                            Ok(Response::builder()
                                .status(StatusCode::INTERNAL_SERVER_ERROR)
                                .body(Body::from("Internal Server Error"))
                                .unwrap())
                        }
                    }
                },
                HandlerResponseKind::RawResponse => quote! {
                    match #handler_call {
                        Ok(mut forte_response) => {
                            let stripped_header_names: Vec<forte_sdk::http::HeaderName> = forte_response
                                .headers()
                                .keys()
                                .filter(|header_name| header_name.as_str().starts_with("x-fn0-"))
                                .cloned()
                                .collect();
                            for header_name in stripped_header_names {
                                forte_response.headers_mut().remove(&header_name);
                            }
                            Ok(build_response_with_cookies(forte_response, &cookie_jar))
                        }
                        Err(error) => {
                            if let Some(redirect) = error.downcast_ref::<Redirect>() {
                                Ok(build_response_with_cookies(
                                    Response::builder()
                                        .status(StatusCode::FOUND)
                                        .header(LOCATION, redirect.to_path())
                                        .body(Body::empty())
                                        .unwrap(),
                                    &cookie_jar,
                                ))
                            } else {
                                eprintln!("Error at {}: {:?}", path, error);
                                Ok(Response::builder()
                                    .status(StatusCode::INTERNAL_SERVER_ERROR)
                                    .body(Body::from("Internal Server Error"))
                                    .unwrap())
                            }
                        }
                    }
                },
                HandlerResponseKind::PropsJson => {
                let ok_response = if page.is_api {
                    quote! {
                        Response::builder()
                            .status(StatusCode::OK)
                            .header("content-type", "application/json")
                            .body(Body::from(body_bytes))
                            .unwrap()
                    }
                } else {
                    quote! {
                        Response::builder()
                            .status(StatusCode::OK)
                            .header("x-fn0-next", "js")
                            .body(Body::from(body_bytes))
                            .unwrap()
                    }
                };
                quote! {
                    match #handler_call {
                        Ok(props) => {
                            let body_bytes = forte_json::to_vec(&props);
                            Ok(build_response_with_cookies(#ok_response, &cookie_jar))
                        }
                        Err(e) => {
                            if let Some(redirect) = e.downcast_ref::<Redirect>() {
                                Ok(build_response_with_cookies(
                                    Response::builder()
                                        .status(StatusCode::FOUND)
                                        .header(LOCATION, redirect.to_path())
                                        .body(Body::empty())
                                        .unwrap(),
                                    &cookie_jar,
                                ))
                            } else {
                                eprintln!("Error at {}: {:?}", path, e);
                                Ok(Response::builder()
                                    .status(StatusCode::INTERNAL_SERVER_ERROR)
                                    .body(Body::from("Internal Server Error"))
                                    .unwrap())
                            }
                        }
                    }
                }
                }
            };

            quote! {
                if #route_condition {
                    #path_params_extraction
                    #search_params_extraction

                    let req = ForteRequest {
                        uri_authority,
                        method: &method,
                        headers: &headers,
                        jar: &mut cookie_jar,
                        raw_body: &[],
                        body,
                    };

                    #response_handling
                }
            }
        })
        .collect()
}

fn generate_dynamic_route_condition(segments: &[RouteSegment]) -> TokenStream {
    let segment_count = segments.len();
    let segment_checks: Vec<TokenStream> = segments
        .iter()
        .enumerate()
        .filter_map(|(i, seg)| {
            if let RouteSegment::Static(s) = seg {
                if i == 0 {
                    Some(quote! { path_segments.first() == Some(&#s) })
                } else {
                    Some(quote! { path_segments.get(#i) == Some(&#s) })
                }
            } else {
                None // Dynamic segments match anything
            }
        })
        .collect();

    if segment_checks.is_empty() {
        quote! {
            path_segments.len() == #segment_count
        }
    } else {
        quote! {
            path_segments.len() == #segment_count && #(#segment_checks)&&*
        }
    }
}

fn generate_path_params_extraction(
    module_name: &syn::Ident,
    route_segments: &[RouteSegment],
    path_params: &[PathParamField],
) -> TokenStream {
    let extractions: Vec<TokenStream> = route_segments
        .iter()
        .enumerate()
        .filter_map(|(i, seg)| {
            if let RouteSegment::Dynamic(param_name) = seg {
                // Find the corresponding PathParamField
                let field = path_params.iter().find(|f| &f.name == param_name)?;
                let field_ident = format_ident!("{}", field.name);
                let inner_type: TokenStream = field.inner_type.parse().unwrap();

                if field.inner_type == "String" {
                    Some(quote! {
                        let #field_ident: String = path_segments[#i].to_string();
                    })
                } else {
                    Some(quote! {
                        let #field_ident: #inner_type = match path_segments[#i].parse::<#inner_type>() {
                            Ok(v) => v,
                            Err(_) => {
                                return Ok(Response::builder()
                                    .status(StatusCode::BAD_REQUEST)
                                    .body(Body::from(format!("Invalid path parameter: {}", stringify!(#field_ident))))
                                    .unwrap());
                            }
                        };
                    })
                }
            } else {
                None
            }
        })
        .collect();

    let field_names: Vec<_> = path_params
        .iter()
        .map(|f| format_ident!("{}", f.name))
        .collect();

    quote! {
        #(#extractions)*
        let path_params = #module_name::PathParams { #(#field_names),* };
    }
}

fn generate_search_field_parsers(fields: &[SearchParamField]) -> Vec<TokenStream> {
    fields
        .iter()
        .map(|field| {
            let field_name = format_ident!("{}", field.name);
            let field_name_str = &field.name;
            let inner_type: TokenStream = field.inner_type.parse().unwrap();

            if field.is_optional {
                if field.inner_type == "String" {
                    quote! {
                        let #field_name: Option<String> = query_params.get(#field_name_str).cloned();
                    }
                } else {
                    quote! {
                        let #field_name: Option<#inner_type> = query_params
                            .get(#field_name_str)
                            .and_then(|v| v.parse::<#inner_type>().ok());
                    }
                }
            } else if field.inner_type == "String" {
                quote! {
                    let Some(#field_name) = query_params.get(#field_name_str).cloned() else {
                        return Ok(Response::builder()
                            .status(StatusCode::BAD_REQUEST)
                            .body(Body::from(format!("Missing required query parameter: {}", #field_name_str)))
                            .unwrap());
                    };
                }
            } else {
                quote! {
                    let #field_name: #inner_type = match query_params.get(#field_name_str) {
                        Some(v) => match v.parse::<#inner_type>() {
                            Ok(parsed) => parsed,
                            Err(_) => {
                                return Ok(Response::builder()
                                    .status(StatusCode::BAD_REQUEST)
                                    .body(Body::from(format!("Invalid value for query parameter: {}", #field_name_str)))
                                    .unwrap());
                            }
                        },
                        None => {
                            return Ok(Response::builder()
                                .status(StatusCode::BAD_REQUEST)
                                .body(Body::from(format!("Missing required query parameter: {}", #field_name_str)))
                                .unwrap());
                        }
                    };
                }
            }
        })
        .collect()
}

fn generate_redirect_enum(pages: &[PageInfo]) -> TokenStream {
    let variants: Vec<TokenStream> = pages
        .iter()
        .map(|page| {
            let variant_name = page_to_variant_name(&page.route_segments);
            let variant_ident = format_ident!("{}", variant_name);

            if let Some(path_params) = &page.path_params {
                let fields: Vec<TokenStream> = path_params
                    .iter()
                    .map(|p| {
                        let name = format_ident!("{}", p.name);
                        let ty: TokenStream = p.inner_type.parse().unwrap();
                        quote! { #name: #ty }
                    })
                    .collect();
                quote! { #variant_ident { #(#fields),* } }
            } else {
                quote! { #variant_ident }
            }
        })
        .collect();

    let to_path_arms: Vec<TokenStream> = pages
        .iter()
        .map(|page| {
            let variant_name = page_to_variant_name(&page.route_segments);
            let variant_ident = format_ident!("{}", variant_name);

            if let Some(path_params) = &page.path_params {
                let field_names: Vec<_> = path_params
                    .iter()
                    .map(|p| format_ident!("{}", p.name))
                    .collect();

                // Build path with dynamic segments
                let path_parts: Vec<TokenStream> = page
                    .route_segments
                    .iter()
                    .map(|seg| match seg {
                        RouteSegment::Static(s) => quote! { #s.to_string() },
                        RouteSegment::Dynamic(name) => {
                            let name_ident = format_ident!("{}", name);
                            quote! { #name_ident.to_string() }
                        }
                    })
                    .collect();

                quote! {
                    Redirect::#variant_ident { #(#field_names),* } => {
                        format!("/{}", [#(#path_parts),*].join("/"))
                    }
                }
            } else {
                let route_path = &page.route_path;
                quote! {
                    Redirect::#variant_ident => #route_path.to_string()
                }
            }
        })
        .collect();

    quote! {
        #[derive(Debug, serde::Serialize, serde::Deserialize)]
        #[allow(non_camel_case_types)]
        pub enum Redirect {
            External { url: String },
            #(#variants),*
        }

        impl Redirect {
            pub fn to_path(&self) -> String {
                match self {
                    Redirect::External { url } => url.clone(),
                    #(#to_path_arms),*
                }
            }
        }

        impl std::fmt::Display for Redirect {
            fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
                write!(f, "Redirect to {}", self.to_path())
            }
        }

        impl std::error::Error for Redirect {}
    }
}

fn page_to_variant_name(segments: &[RouteSegment]) -> String {
    // /post -> Post
    // /post/id (static) -> PostId
    // /post/[id] -> Post_id_
    // /post/[id]/comment -> Post_id_Comment
    if segments.is_empty() {
        return "Index".to_string();
    }

    segments
        .iter()
        .map(|seg| match seg {
            RouteSegment::Static(s) => {
                let mut chars = s.chars();
                match chars.next() {
                    None => String::new(),
                    Some(first) => first.to_uppercase().collect::<String>() + chars.as_str(),
                }
            }
            RouteSegment::Dynamic(name) => {
                format!("_{}_", name)
            }
        })
        .collect()
}

fn generate_hook_handler(hooks: &[HookInfo]) -> TokenStream {
    if hooks.is_empty() {
        return quote! {
            async fn handle_hook(
                hook_name: &str,
                _uri_authority: &str,
                _method: &http::Method,
                _headers: &HeaderMap,
                _cookie_jar: &mut cookie::CookieJar,
                _body_bytes: &[u8],
            ) -> Result<Response<Body>> {
                Ok(Response::builder()
                    .status(StatusCode::NOT_FOUND)
                    .body(Body::from(format!("Hook '{}' not found", hook_name)))
                    .unwrap())
            }
        };
    }

    let hook_matches: Vec<TokenStream> = hooks
        .iter()
        .map(|hook| {
            let name = &hook.name;
            let module_name = format_ident!("{}", hook.module_name);

            quote! {
                #name => {
                    let input: #module_name::Input = forte_json::from_slice(body_bytes)?;
                    let req = ForteRequest {
                        uri_authority,
                        method,
                        headers,
                        jar: cookie_jar,
                        raw_body: body_bytes,
                        body: input,
                    };
                    let output = #module_name::handler(req).await;
                    let json = forte_json::to_vec(&output);
                    Ok(build_response_with_cookies(
                        Response::builder()
                            .status(StatusCode::OK)
                            .header("content-type", "application/json")
                            .body(Body::from(json))
                            .unwrap(),
                        cookie_jar,
                    ))
                }
            }
        })
        .collect();

    quote! {
        #[forte_sdk::tracing::instrument(
            name = "handle_hook",
            skip_all,
            fields(hook = hook_name),
        )]
        async fn handle_hook(
            hook_name: &str,
            uri_authority: &str,
            method: &http::Method,
            headers: &HeaderMap,
            cookie_jar: &mut cookie::CookieJar,
            body_bytes: &[u8],
        ) -> Result<Response<Body>> {
            match hook_name {
                #(#hook_matches)*
                _ => Ok(Response::builder()
                    .status(StatusCode::NOT_FOUND)
                    .body(Body::from(format!("Hook '{}' not found", hook_name)))
                    .unwrap()),
            }
        }
    }
}

fn generate_action_module_declarations(_actions: &[ActionInfo]) -> Vec<(String, TokenStream)> {
    Vec::new()
}

fn generate_action_handler(actions: &[ActionInfo]) -> TokenStream {
    if actions.is_empty() {
        return quote! {
            async fn handle_action(
                action_name: &str,
                _uri_authority: &str,
                _method: &http::Method,
                _headers: &HeaderMap,
                _cookie_jar: &mut cookie::CookieJar,
                _body_bytes: &[u8],
            ) -> Result<Response<Body>> {
                Ok(Response::builder()
                    .status(StatusCode::NOT_FOUND)
                    .body(Body::from(format!("Action '{}' not found", action_name)))
                    .unwrap())
            }
        };
    }

    let action_matches: Vec<TokenStream> = actions
        .iter()
        .map(|action| {
            let name = &action.name;
            let module_ident = format_ident!("{}", action.name);

            quote! {
                #name => {
                    let input: crate::actions::#module_ident::Input = match forte_json::from_slice(body_bytes) {
                        Ok(v) => v,
                        Err(e) => {
                            return Ok(Response::builder()
                                .status(StatusCode::BAD_REQUEST)
                                .body(Body::from(format!("invalid request body: {}", e)))
                                .unwrap());
                        }
                    };
                    let req = ForteRequest {
                        uri_authority,
                        method,
                        headers,
                        jar: cookie_jar,
                        raw_body: body_bytes,
                        body: input,
                    };
                    let output = crate::actions::#module_ident::handler(req).await;
                    let json = forte_json::to_vec(&output);
                    Ok(build_response_with_cookies(
                        Response::builder()
                            .status(StatusCode::OK)
                            .header("content-type", "application/json")
                            .body(Body::from(json))
                            .unwrap(),
                        cookie_jar,
                    ))
                }
            }
        })
        .collect();

    quote! {
        #[forte_sdk::tracing::instrument(
            name = "handle_action",
            skip_all,
            fields(action = action_name),
        )]
        async fn handle_action(
            action_name: &str,
            uri_authority: &str,
            method: &http::Method,
            headers: &HeaderMap,
            cookie_jar: &mut cookie::CookieJar,
            body_bytes: &[u8],
        ) -> Result<Response<Body>> {
            match action_name {
                #(#action_matches)*
                _ => Ok(Response::builder()
                    .status(StatusCode::NOT_FOUND)
                    .body(Body::from(format!("Action '{}' not found", action_name)))
                    .unwrap()),
            }
        }
    }
}

fn generate_enqueue_module(queue_tasks: &[QueueTaskInfo]) -> TokenStream {
    if queue_tasks.is_empty() {
        return quote! {};
    }

    let enqueue_fns: Vec<TokenStream> = queue_tasks
        .iter()
        .map(|qt| {
            let fn_name = format_ident!("{}", qt.name);
            let task_name_str = &qt.name;
            let module_path: Vec<_> = vec![format_ident!("queue_task"), format_ident!("{}", qt.name)];

            quote! {
                pub async fn #fn_name(input: crate::#(#module_path)::*::Input) -> forte_sdk::anyhow::Result<()> {
                    let payload = forte_sdk::serde_json::to_value(&input)?;
                    let body = forte_sdk::serde_json::to_vec(&forte_sdk::serde_json::json!({
                        "task_name": #task_name_str,
                        "payload": payload,
                    }))?;
                    let url = std::env::var("FN0_QUEUE_URL")
                        .map_err(|_| forte_sdk::anyhow::anyhow!("FN0_QUEUE_URL is not set"))?;
                    let request = forte_sdk::http::Request::post(&url)
                        .header("Content-Type", "application/json")
                        .body(body)?;
                    let response = forte_sdk::http::Client::new().send(request).await?;
                    if !response.status().is_success() {
                        return Err(forte_sdk::anyhow::anyhow!(
                            "enqueue failed with status {}",
                            response.status()
                        ));
                    }
                    Ok(())
                }
            }
        })
        .collect();

    quote! {
        pub mod enqueue {
            #(#enqueue_fns)*
        }
    }
}

fn generate_queue_task_execute_handler(queue_tasks: &[QueueTaskInfo]) -> TokenStream {
    if queue_tasks.is_empty() {
        return quote! {
            async fn handle_queue_task_execute(
                _body_bytes: &[u8],
            ) -> Result<Response<Body>> {
                Ok(Response::builder()
                    .status(StatusCode::NOT_FOUND)
                    .body(Body::from("No queue tasks defined"))
                    .unwrap())
            }
        };
    }

    let task_matches: Vec<TokenStream> = queue_tasks
        .iter()
        .map(|qt| {
            let name = &qt.name;
            let module_path: Vec<_> =
                vec![format_ident!("queue_task"), format_ident!("{}", qt.name)];

            quote! {
                #name => {
                    let input: crate::#(#module_path)::*::Input =
                        match forte_sdk::serde_json::from_value(payload.clone()) {
                            Ok(v) => v,
                            Err(e) => {
                                return Ok(Response::builder()
                                    .status(StatusCode::BAD_REQUEST)
                                    .body(Body::from(format!("invalid payload for task '{}': {}", task_name, e)))
                                    .unwrap());
                            }
                        };
                    crate::#(#module_path)::*::handle(input).await
                }
            }
        })
        .collect();

    quote! {
        async fn handle_queue_task_execute(
            body_bytes: &[u8],
        ) -> Result<Response<Body>> {
            let request: forte_sdk::serde_json::Value = match forte_sdk::serde_json::from_slice(body_bytes) {
                Ok(v) => v,
                Err(e) => {
                    return Ok(Response::builder()
                        .status(StatusCode::BAD_REQUEST)
                        .body(Body::from(format!("invalid request body: {}", e)))
                        .unwrap());
                }
            };
            let task_name = match request["task_name"].as_str() {
                Some(s) => s,
                None => {
                    return Ok(Response::builder()
                        .status(StatusCode::BAD_REQUEST)
                        .body(Body::from("missing or non-string task_name"))
                        .unwrap());
                }
            };
            let payload = &request["payload"];

            let result = match task_name {
                #(#task_matches)*
                _ => {
                    return Ok(Response::builder()
                        .status(StatusCode::NOT_FOUND)
                        .body(Body::from(format!("Queue task '{}' not found", task_name)))
                        .unwrap());
                }
            };

            match result {
                Ok(()) => Ok(Response::builder()
                    .status(StatusCode::OK)
                    .body(Body::empty())
                    .unwrap()),
                Err(e) => Ok(Response::builder()
                    .status(StatusCode::INTERNAL_SERVER_ERROR)
                    .body(Body::from(format!("{:?}", e)))
                    .unwrap()),
            }
        }
    }
}

fn generate_admin_task_handler(admin_tasks: &[AdminTaskInfo]) -> TokenStream {
    if admin_tasks.is_empty() {
        return quote! {
            async fn handle_admin_task(
                _task_name: &str,
                _headers: &HeaderMap,
                _body_bytes: &[u8],
            ) -> Result<Response<Body>> {
                Ok(Response::builder()
                    .status(StatusCode::NOT_FOUND)
                    .body(Body::from("No admin tasks defined"))
                    .unwrap())
            }
        };
    }

    let task_matches: Vec<TokenStream> = admin_tasks
        .iter()
        .map(|at| {
            let name = &at.name;
            let module_path: Vec<_> = vec![format_ident!("admin"), format_ident!("{}", at.name)];

            quote! {
                #name => {
                    let input: crate::#(#module_path)::*::Input =
                        forte_sdk::serde_json::from_slice(body_bytes)?;
                    let output = crate::#(#module_path)::*::handle(input).await;
                    match output {
                        Ok(value) => {
                            let json = forte_sdk::serde_json::to_vec(&value)?;
                            Ok(Response::builder()
                                .status(StatusCode::OK)
                                .header("content-type", "application/json")
                                .body(Body::from(json))
                                .unwrap())
                        }
                        Err(e) => Ok(Response::builder()
                            .status(StatusCode::INTERNAL_SERVER_ERROR)
                            .body(Body::from(format!("{:?}", e)))
                            .unwrap()),
                    }
                }
            }
        })
        .collect();

    quote! {
        #[forte_sdk::tracing::instrument(
            name = "handle_admin_task",
            skip_all,
            fields(task = task_name),
        )]
        async fn handle_admin_task(
            task_name: &str,
            headers: &HeaderMap,
            body_bytes: &[u8],
        ) -> Result<Response<Body>> {
            let is_admin = headers
                .get("x-fn0-admin")
                .and_then(|v| v.to_str().ok())
                .map(|v| v == "true")
                .unwrap_or(false);
            if !is_admin {
                return Ok(Response::builder()
                    .status(StatusCode::UNAUTHORIZED)
                    .body(Body::from("Unauthorized"))
                    .unwrap());
            }

            match task_name {
                #(#task_matches)*
                _ => Ok(Response::builder()
                    .status(StatusCode::NOT_FOUND)
                    .body(Body::from(format!("Admin task '{}' not found", task_name)))
                    .unwrap()),
            }
        }
    }
}

fn generate_classify_route(pages: &[PageInfo]) -> TokenStream {
    let arms: Vec<TokenStream> = pages
        .iter()
        .map(|p| {
            let route_path = &p.route_path;
            if has_dynamic_segments(&p.route_segments) {
                let len = p.route_segments.len();
                let static_checks: Vec<TokenStream> = p
                    .route_segments
                    .iter()
                    .enumerate()
                    .filter_map(|(i, seg)| match seg {
                        RouteSegment::Static(s) => Some(quote! { path_segments[#i] == #s }),
                        RouteSegment::Dynamic(_) => None,
                    })
                    .collect();
                if static_checks.is_empty() {
                    quote! {
                        if path_segments.len() == #len {
                            return #route_path.to_string();
                        }
                    }
                } else {
                    quote! {
                        if path_segments.len() == #len && #(#static_checks)&&* {
                            return #route_path.to_string();
                        }
                    }
                }
            } else {
                quote! {
                    if path == #route_path {
                        return #route_path.to_string();
                    }
                }
            }
        })
        .collect();

    let needs_path_segments = pages
        .iter()
        .any(|p| has_dynamic_segments(&p.route_segments));
    let path_segments_decl = if needs_path_segments {
        quote! {
            let path_segments: Vec<&str> = path.trim_start_matches('/').split('/').collect();
        }
    } else {
        quote! {}
    };

    quote! {
        fn classify_route(path: &str) -> String {
            if path.strip_prefix("/__forte_action/").is_some() {
                return "/__forte_action/[name]".to_string();
            }
            if path.strip_prefix("/__forte_admin/").is_some() {
                return "/__forte_admin/[name]".to_string();
            }
            if path == "/__fn0_queue_task/execute" {
                return "/__fn0_queue_task/execute".to_string();
            }
            if path == "/__fn0_cache_policy" {
                return "/__fn0_cache_policy".to_string();
            }
            if path.strip_prefix("/__self_invoke/").is_some() {
                return "/__self_invoke/[name]".to_string();
            }
            #path_segments_decl
            #(#arms)*
            "unknown".to_string()
        }
    }
}

// Same extraction as the page route, except a parameter that fails to parse
// means "not a cacheable path" rather than a 400: the preflight only decides
// caching, and the page handler still gets to answer the request.
fn generate_cache_policy_path_params(
    module_name: &syn::Ident,
    route_segments: &[RouteSegment],
    path_params: &[PathParamField],
    not_cacheable: &TokenStream,
) -> TokenStream {
    let extractions: Vec<TokenStream> = route_segments
        .iter()
        .enumerate()
        .filter_map(|(segment_index, segment)| {
            let RouteSegment::Dynamic(param_name) = segment else {
                return None;
            };
            let field = path_params.iter().find(|f| &f.name == param_name)?;
            let field_ident = format_ident!("{}", field.name);
            if field.inner_type == "String" {
                return Some(quote! {
                    let #field_ident: String = path_segments[#segment_index].to_string();
                });
            }
            let inner_type: TokenStream = field.inner_type.parse().unwrap();
            Some(quote! {
                let Ok(#field_ident) = path_segments[#segment_index].parse::<#inner_type>() else {
                    return #not_cacheable;
                };
            })
        })
        .collect();

    let field_names: Vec<_> = path_params
        .iter()
        .map(|f| format_ident!("{}", f.name))
        .collect();

    quote! {
        #(#extractions)*
        let path_params = #module_name::PathParams { #(#field_names),* };
    }
}

fn generate_cache_policy_handler(pages: &[PageInfo]) -> TokenStream {
    let static_pages: Vec<&PageInfo> = pages.iter().filter(|page| page.cache_static).collect();
    for page in &static_pages {
        // One concrete path is one stored object, so a dynamic route without a
        // validator lets any probed path write one. The page owns the
        // knowledge of which ids exist, so it has to answer.
        if has_dynamic_segments(&page.route_segments) && !page.has_cache_static_eligible {
            panic!(
                "cache_static on dynamic route {} requires `pub async fn cache_static_eligible(params: PathParams) -> anyhow::Result<bool>` in the same module",
                page.route_path
            );
        }
        if page.is_api {
            panic!(
                "cache_static cannot be used on API route {}",
                page.route_path
            );
        }
        if page.response_kind == HandlerResponseKind::RedirectOnly {
            panic!(
                "cache_static cannot be used on redirect route {}",
                page.route_path
            );
        }
    }

    let cacheable = quote! {
        Ok(Response::builder()
            .status(StatusCode::NO_CONTENT)
            .header("x-fn0-cache-policy", "static")
            .body(Body::empty())
            .unwrap())
    };
    let not_cacheable = quote! {
        Ok(Response::builder()
            .status(StatusCode::NOT_FOUND)
            .body(Body::empty())
            .unwrap())
    };

    let exact_checks: Vec<TokenStream> = static_pages
        .iter()
        .filter(|page| !has_dynamic_segments(&page.route_segments))
        .map(|page| {
            let route_path = &page.route_path;
            quote! { target_path == #route_path }
        })
        .collect();
    let exact_policy = if exact_checks.is_empty() {
        quote! {}
    } else {
        quote! {
            if #(#exact_checks)||* {
                return #cacheable;
            }
        }
    };

    let dynamic_arms: Vec<TokenStream> = static_pages
        .iter()
        .filter(|page| has_dynamic_segments(&page.route_segments))
        .map(|page| {
            let module_name = format_ident!("{}", page.module_name);
            let route_path = &page.route_path;
            let Some(path_params) = &page.path_params else {
                panic!(
                    "cache_static on dynamic route {route_path} requires a PathParams struct to pass to cache_static_eligible",
                );
            };
            let condition = generate_dynamic_route_condition(&page.route_segments);
            let extraction = generate_cache_policy_path_params(
                &module_name,
                &page.route_segments,
                path_params,
                &not_cacheable,
            );
            quote! {
                if #condition {
                    #extraction
                    let eligible = match #module_name::cache_static_eligible(path_params).await {
                        Ok(eligible) => eligible,
                        Err(error) => {
                            tracing::warn!(%error, route = #route_path, "cache_static_eligible failed");
                            false
                        }
                    };
                    if eligible {
                        return #cacheable;
                    }
                    return #not_cacheable;
                }
            }
        })
        .collect();
    let dynamic_policy = if dynamic_arms.is_empty() {
        quote! {}
    } else {
        quote! {
            let path_segments: Vec<&str> = target_path.trim_start_matches('/').split('/').collect();
            #(#dynamic_arms)*
        }
    };

    let static_policy = if static_pages.is_empty() {
        quote! { let _ = headers; }
    } else {
        quote! {
            let Some(target_path) = headers
                .get("x-fn0-cache-path")
                .and_then(|value| value.to_str().ok())
            else {
                return #not_cacheable;
            };

            #exact_policy
            #dynamic_policy
        }
    };

    quote! {
        async fn handle_cache_policy(
            method: &forte_sdk::http::Method,
            headers: &HeaderMap,
        ) -> Result<Response<Body>> {
            if method != forte_sdk::http::Method::POST {
                return #not_cacheable;
            }

            #static_policy

            #not_cacheable
        }
    }
}

pub(super) fn generate_admin_mod(admin_tasks: &[AdminTaskInfo]) -> String {
    let mut content = String::new();
    content.push_str("// Auto-generated by forte build\n\n");
    let mut names: Vec<&str> = admin_tasks.iter().map(|a| a.name.as_str()).collect();
    names.sort();
    for name in names {
        content.push_str(&format!("pub mod {};\n", name));
    }
    content
}

pub(super) fn generate_actions_mod(actions: &[ActionInfo]) -> String {
    let mut content = String::new();
    content.push_str("// Auto-generated by forte build\n\n");
    let mut names: Vec<&str> = actions.iter().map(|a| a.name.as_str()).collect();
    names.sort();
    for name in names {
        content.push_str(&format!("pub mod {};\n", name));
    }
    content
}

pub(super) fn generate_queue_task_mod(queue_tasks: &[QueueTaskInfo]) -> String {
    let mut content = String::new();
    content.push_str("// Auto-generated by forte build\n\n");
    let mut names: Vec<&str> = queue_tasks.iter().map(|q| q.name.as_str()).collect();
    names.sort();
    for name in names {
        content.push_str(&format!("pub mod {};\n", name));
    }
    content
}

pub(super) fn generate_fe_paths(pages: &[PageInfo]) -> String {
    let mut content = String::new();
    content.push_str("// Auto-generated by forte build\n\n");
    content.push_str("export const paths = {\n");

    for page in pages {
        // Convert [id] to :id format for the key
        let route_path = page
            .route_segments
            .iter()
            .map(|seg| match seg {
                RouteSegment::Static(s) => s.clone(),
                RouteSegment::Dynamic(name) => format!(":{}", name),
            })
            .collect::<Vec<_>>();
        let route_path = if route_path.is_empty() {
            "/".to_string()
        } else {
            format!("/{}", route_path.join("/"))
        };

        if let Some(path_params) = &page.path_params {
            // Has dynamic params: "/post/:id": ({id}: {id: string}) => `/post/${id}`
            let param_names: Vec<&str> = path_params.iter().map(|p| p.name.as_str()).collect();
            let param_types: Vec<String> = path_params
                .iter()
                .map(|p| format!("{}: {}", p.name, rust_type_to_ts(&p.inner_type)))
                .collect();

            let path_template = page
                .route_segments
                .iter()
                .map(|seg| match seg {
                    RouteSegment::Static(s) => s.clone(),
                    RouteSegment::Dynamic(name) => format!("${{{}}}", name),
                })
                .collect::<Vec<_>>()
                .join("/");

            content.push_str(&format!(
                "  \"{}\": ({{{}}}: {{{}}}) => `/{}`",
                route_path,
                param_names.join(", "),
                param_types.join("; "),
                path_template
            ));
        } else {
            // No params: "/": () => "/"
            content.push_str(&format!("  \"{}\": () => \"{}\"", route_path, route_path));
        }

        content.push_str(",\n");
    }

    content.push_str("} as const;\n");
    content
}

fn rust_type_to_ts(rust_type: &str) -> &str {
    match rust_type {
        "String" | "&str" => "string",
        "i8" | "i16" | "i32" | "i64" | "u8" | "u16" | "u32" | "u64" | "f32" | "f64" | "isize"
        | "usize" => "number",
        "bool" => "boolean",
        _ => "string",
    }
}
