[package]
name = "forte-json"
version = "0.1.3"
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Streaming JSON serializer for the Forte web framework"

[dependencies]
bytes = { workspace = true }
futures = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

[dev-dependencies]
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
tokio = { workspace = true, features = ["full"] }
